FROM golang:1.19.4-bullseye

RUN apt-get update && \
  apt-get install -y build-essential && \
  apt-get install -y unzip && \
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
  unzip awscliv2.zip && \
  ./aws/install

RUN mkdir /bot
WORKDIR /bot

RUN go install github.com/pilu/fresh@latest

COPY . .

EXPOSE 8080

CMD fresh
