FROM golang:1.19.4-bullseye

RUN apt-get update && \
  apt-get install -y build-essential && \
  apt-get install -y unzip && \
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
  unzip awscliv2.zip && \
  ./aws/install

ENV KANVAS_VERSION=0.8.0

RUN apt install -y curl \
    && curl -LO https://github.com/davinci-std/kanvas/releases/download/v${KANVAS_VERSION}/kanvas_${KANVAS_VERSION}_linux_amd64.tar.gz \
    && tar -xzf kanvas_${KANVAS_VERSION}_linux_amd64.tar.gz \
    && mv kanvas /usr/local/bin/kanvas \
    && rm kanvas_${KANVAS_VERSION}_linux_amd64.tar.gz

RUN mkdir /bot
WORKDIR /bot

RUN go install github.com/pilu/fresh@latest

COPY . .

EXPOSE 8080

CMD fresh
